---

sw1:
  hostname: 192.168.51.31
  platform: nxos
  groups:
    - cisco
    - spine

sw2:
  hostname: 192.168.51.32
  platform: nxos
  groups:
    - cisco
    - spine

sw3:
  hostname: 192.168.51.33
  platform: nxos
  groups:
    - cisco
    - leaf

sw4:
  hostname: 192.168.51.34
  platform: nxos
  groups:
    - cisco
    - leaf
    - static

sw5:
  hostname: 192.168.51.35
  platform: nxos
  groups:
    - cisco
    - leaf
    - static

sw6:
  hostname: 192.168.51.36
  platform: nxos
  groups:
    - cisco
    - leaf


sw7:
  hostname: 192.168.51.37
  platform: nxos
  groups:
    - cisco
    - static

sw8:
  hostname: 192.168.51.38
  platform: nxos
  groups:
    - cisco
    - static